### ISSUE TITLE
Format of your mammogram data

### ISSUE THREAD

**Issue by emrekeles-arch** [prithuls/MV-SWIN-T#3]
Is the mammogram data you use with a DICOM extension or a PNG extension?

**Comment by prithuls** [comment]
Hi, thanks for your interest in our research.

The data we used have PNG extension. Some of the preprocessing steps (from converting DICOM to PNG) can be found in this repo: https://github.com/CleonWong/Can-You-Find-The-Tumour/tree/master

Thanks.
